import React from 'react'

const Cards = () => {
    const plants =[
        {   id: 1,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 2,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 3,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 4,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 5,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 6,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 7,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 8,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 9,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 10,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 11,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 12,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 13,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 15,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 16,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 17,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 18,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 19,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        {   id: 20,
            name: "Aloe Vera",
            image: "/aloe.png",
            description: "Aloe is a medicinal plant",
            uses: "To treat skin conditions",
        },
        
    ]
    return (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4 w-full">
          {plants.map((plant) => (
            <div key={plant.id} className="bg-green-200 rounded-lg p-4 shadow-md flex flex-col items-center">
              <img src={plant.image} alt={plant.name} className="w-32 h-32 object-cover mb-4" />
              <h1 className="text-lg font-bold mb-2">{plant.name}</h1>
              <p className="text-sm text-gray-700 mb-4">{plant.description}</p>
              <button className="bg-orange-400 text-white py-2 px-4 rounded">Explore!</button>
            </div>
          ))}
        </div>
      );

}

export default Cards